package Group2A.SDMS.Services;

import Group2A.SDMS.Entities.Users;
import Group2A.SDMS.Repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.transaction.Transaction;
import java.util.List;

@Service
@Transactional
public class UserService {

    @Autowired// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public List<Users> getAllUsers(){
        return userRepository.getAllUsers();
    }

    public void save(Users user){ userRepository.save(user); }

    public void deleteUserByID(int userID){
        userRepository.deleteUserByID(userID);
    }

    public void saveUser(Users user){
        userRepository.save(user);
    }

    public void editUser(String username, String email, String firstname, String lastname, String address,
                         double wage){ userRepository.editUser(username, email, firstname, lastname, address, wage); }

    public Users getUserByUsername(String username){
       return userRepository.findByUsername(username);
    }
}
