package Group2A.SDMS.Controllers;

import Group2A.SDMS.Entities.Users;
import Group2A.SDMS.Repositories.UserRepository;
import Group2A.SDMS.Services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class TestingController {

    @Autowired// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserService userService;

    @GetMapping("/addTestUser")
    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name);

        Users user = new Users();

        user.setUsername("Admin");
        String password = "Admin";
        BCryptPasswordEncoder bcp = new BCryptPasswordEncoder();
        user.setPassword(bcp.encode(password));
        user.setFirstname("Group");
        user.setLastname("2A");
        user.setEmail("Interesting@Example.Com");
        user.setAddress("Somewhere, Someplace.");
        user.setAccessLevel("ADMIN");
        user.setTotalPoints(0);
        user.setWage(0);

        userService.saveUser(user);

        return "greeting";
    }

}
